default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  username: postgres
  password: n673927826
  pool: 5

development:
  <<: *default
  database: blog_app_db

test:
  <<: *default
  database: blog_app_db_test

production:
  <<: *default
  database: blog_app_db_production